# Generated by Django 5.0.1 on 2024-02-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="slider")),
                ("link", models.URLField(max_length=256)),
            ],
            options={
                "verbose_name": "Слайдер",
                "verbose_name_plural": "Слайдеры",
            },
        ),
    ]
