# Generated by Django 5.0.1 on 2024-02-05 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_newscategory_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
